package com.ht.vis.query;

import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.core.CoreQuery;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CDepartmentQuery extends CoreQuery {
    private String cCode;

    public String getcCode() {
        return cCode;
    }

    public void setcCode(String cCode) {
        this.cCode = cCode;
    }

}