package com.ht.vis.query;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CInfoQuery extends CoreQuery {
    private java.lang.String name;
    public void setName(java.lang.String name){
        this.name=name;
    }
    public java.lang.String getName(){
        return this.name;
    }
    private java.lang.String code;
    public void setCode(java.lang.String code){
        this.code=code;
    }
    public java.lang.String getCode(){
        return this.code;
    }
    private java.lang.String cNo;
    public void setCNo(java.lang.String cNo){
        this.cNo=cNo;
    }
    public java.lang.String getCNo(){
        return this.cNo;
    }
    private java.lang.Integer cType;
    public void setCType(java.lang.Integer cType){
        this.cType=cType;
    }
    public java.lang.Integer getCType(){
        return this.cType;
    }
    private java.lang.String bType;
    public void setBType(java.lang.String bType){
        this.bType=bType;
    }
    public java.lang.String getBType(){
        return this.bType;
    }
    private java.lang.String tel;
    public void setTel(java.lang.String tel){
        this.tel=tel;
    }
    public java.lang.String getTel(){
        return this.tel;
    }


}