package com.ht.vis.query;
import com.ht.vis.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CMeetingQuery extends CoreQuery {

        private String title;
        public void setTitle(String title){
                this.title=title;
        }
        public String getTitle(){
            return this.title;
        }
        private String type;
        public void setType(String type){
                this.type=type;
        }
        public String getType(){
            return this.type;
        }


}