package com.ht.vis.query;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.core.CoreQuery;
import com.ht.vis.kits.DateKit;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CMeetingQuery extends CoreQuery {

        private java.lang.String title;
        public void setTitle(java.lang.String title){
                this.title=title;
        }
        public java.lang.String getTitle(){
                return this.title;
        }
        private java.lang.String type;
        public void setType(java.lang.String type){
                this.type=type;
        }
        public java.lang.String getType(){
                return this.type;
        }
        //mAt比较的开始时间
        private String beginMAt;
        //mAt比较的结束时间
        private String endMAt;
        public String getBeginMAt(){
                return StrUtil.isNotBlank(this.beginMAt)? DateKit.getDateTimeBegin(this.beginMAt):null;
        }
        public void setBeginMAt(String begin){
                this.beginMAt=begin;
        }

        public String getEndMAt(){
                return StrUtil.isNotBlank(this.endMAt)?DateKit.getDateTimeEnd(this.endMAt):null;
        }
        public void setEndMAt(String end){
                this.endMAt=end;
        }


}