package com.ht.vis.query;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class RoleQuery extends CoreQuery {

        private String name;
        public void setName(String name){
                this.name=name;
        }
        public String getName(){
            return this.name;
        }
        private String code;
        public void setCode(String code){
                this.code=code;
        }
        public String getCode(){
            return this.code;
        }


}