package com.ht.vis.query;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class SerQuery extends CoreQuery {

        private String code;
        public void setCode(String code){
                this.code=code;
        }
        public String getCode(){
            return this.code;
        }
        private String name;
        public void setName(String name){
                this.name=name;
        }
        public String getName(){
            return this.name;
        }
        private Integer pId;

        public Integer getpId() {
                return pId;
        }

        public void setpId(Integer pId) {
                this.pId = pId;
        }
}