package com.ht.vis.query;

import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.core.CoreQuery;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class SpAssessmentCriteriaQuery extends CoreQuery {

    private Integer norm;

    public void setNorm(Integer norm) {
        this.norm = norm;
    }

    public Integer getNorm() {
        return this.norm;
    }

    private Integer title;

    public void setTitle(Integer title) {
        this.title = title;
    }

    public Integer getTitle() {
        return this.title;
    }

    private String stars;

    public void setStars(String stars) {
        this.stars = stars;
    }

    public String getStars() {
        return this.stars;
    }


}