package com.ht.vis.query;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class UserQuery extends CoreQuery {

	private String loginname;
	public void setLoginname(String loginname){
		this.loginname=loginname;
	}
	public String getLoginname(){
		return this.loginname;
	}
	private String nickname;
	public void setNickname(String nickname){
		this.nickname=nickname;
	}
	public String getNickname(){
		return this.nickname;
	}
	private String phone;
	public void setPhone(String phone){
		this.phone=phone;
	}
	public String getPhone(){
		return this.phone;
	}
	private String email;
	public void setEmail(String email){
		this.email=email;
	}
	public String getEmail(){
		return this.email;
	}
	private String status;
	public void setStatus(String status){
		this.status=status;
	}
	public String getStatus(){
		return this.status;
	}
	//cAt比较的开始时间
	private String beginCAt;
	//cAt比较的结束时间
	private String endCAt;
	public String getBeginCAt(){
		return StrUtil.isNotBlank(this.beginCAt)?DateKit.getDateTimeBegin(this.beginCAt):null;
	}
	public void setBeginCAt(String begin){
		this.beginCAt=begin;
	}

	public String getEndCAt(){
		return StrUtil.isNotBlank(this.endCAt)?DateKit.getDateTimeEnd(this.endCAt):null;
	}
	public void setEndCAt(String end){
		this.endCAt=end;
	}
	private String cCode;

	public String getCCode() {
		return cCode;
	}

	public void setCCode(String cCode) {
		this.cCode = cCode;
	}
}