package com.ht.vis.query;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VChangeQuery extends CoreQuery {

        private java.lang.String licensePlate;
        public void setLicensePlate(java.lang.String licensePlate){
                this.licensePlate=licensePlate;
        }
        public java.lang.String getLicensePlate(){
            return this.licensePlate;
        }


}