package com.ht.vis.query;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VChangeQuery extends CoreQuery {

        private java.lang.String licensePlate;
        public void setLicensePlate(java.lang.String licensePlate){
                this.licensePlate=licensePlate;
        }
        public java.lang.String getLicensePlate(){
                return this.licensePlate;
        }
        //changeDate比较的开始时间
        private String beginChangeDate;
        //changeDate比较的结束时间
        private String endChangeDate;
        public String getBeginChangeDate(){
                return StrUtil.isNotBlank(this.beginChangeDate)?DateKit.getDateTimeBegin(this.beginChangeDate):null;
        }
        public void setBeginChangeDate(String begin){
                this.beginChangeDate=begin;
        }

        public String getEndChangeDate(){
                return StrUtil.isNotBlank(this.endChangeDate)?DateKit.getDateTimeEnd(this.endChangeDate):null;
        }
        public void setEndChangeDate(String end){
                this.endChangeDate=end;
        }


}