package com.ht.vis.query;
import com.ht.vis.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VInfoQuery extends CoreQuery {

        private String licensePlate;
        public void setLicensePlate(String licensePlate){
                this.licensePlate=licensePlate;
        }
        public String getLicensePlate(){
            return this.licensePlate;
        }
        private String host;
        public void setHost(String host){
                this.host=host;
        }
        public String getHost(){
            return this.host;
        }
        private String type;
        public void setType(String type){
                this.type=type;
        }
        public String getType(){
            return this.type;
        }
        private String tel;
        public void setTel(String tel){
                this.tel=tel;
        }
        public String getTel(){
            return this.tel;
        }
        private String telx;
        public void setTelx(String telx){
                this.telx=telx;
        }
        public String getTelx(){
            return this.telx;
        }
        private java.util.Date regDate;
        public void setRegDate(java.util.Date regDate){
                this.regDate=regDate;
        }
        public java.util.Date getRegDate(){
            return this.regDate;
        }
        private String line;
        public void setLine(String line){
                this.line=line;
        }
        public String getLine(){
            return this.line;
        }
        private String area;
        public void setArea(String area){
                this.area=area;
        }
        public String getArea(){
            return this.area;
        }
        private String idcard;
        public void setIdcard(String idcard){
                this.idcard=idcard;
        }
        public String getIdcard(){
            return this.idcard;
        }


}