package com.ht.vis.query;

import cn.hutool.core.util.StrUtil;
import com.ht.vis.core.CoreQuery;
import com.ht.vis.kits.DateKit;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VInsuranceQuery extends CoreQuery {

    private java.lang.String licensePlate;
    public void setLicensePlate(java.lang.String licensePlate){
        this.licensePlate=licensePlate;
    }
    public java.lang.String getLicensePlate(){
        return this.licensePlate;
    }
    //bAt比较的开始时间
    private String beginBAt;
    //bAt比较的结束时间
    private String endBAt;
    public String getBeginBAt(){
        return StrUtil.isNotBlank(this.beginBAt)? DateKit.getDateTimeBegin(this.beginBAt):null;
    }
    public void setBeginBAt(String begin){
        this.beginBAt=begin;
    }

    public String getEndBAt(){
        return StrUtil.isNotBlank(this.endBAt)?DateKit.getDateTimeEnd(this.endBAt):null;
    }
    public void setEndBAt(String end){
        this.endBAt=end;
    }

    //eAt比较的开始时间
    private String beginEAt;
    //eAt比较的结束时间
    private String endEAt;
    public String getBeginEAt(){
        return StrUtil.isNotBlank(this.beginEAt)?DateKit.getDateTimeBegin(this.beginEAt):null;
    }
    public void setBeginEAt(String begin){
        this.beginEAt=begin;
    }

    public String getEndEAt(){
        return StrUtil.isNotBlank(this.endEAt)?DateKit.getDateTimeEnd(this.endEAt):null;
    }
    public void setEndEAt(String end){
        this.endEAt=end;
    }

    private java.lang.String num;
    public void setNum(java.lang.String num){
        this.num=num;
    }
    public java.lang.String getNum(){
        return this.num;
    }


}