package com.ht.vis.query;
import com.ht.vis.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VInsuranceQuery extends CoreQuery {

        private String licensePlate;
        public void setLicensePlate(String licensePlate){
                this.licensePlate=licensePlate;
        }
        public String getLicensePlate(){
            return this.licensePlate;
        }
        private java.util.Date bAt;
        public void setBAt(java.util.Date bAt){
                this.bAt=bAt;
        }
        public java.util.Date getBAt(){
            return this.bAt;
        }
        private java.util.Date eAt;
        public void setEAt(java.util.Date eAt){
                this.eAt=eAt;
        }
        public java.util.Date getEAt(){
            return this.eAt;
        }
        private String num;
        public void setNum(String num){
                this.num=num;
        }
        public String getNum(){
            return this.num;
        }
        private Integer opId;
        public void setOpId(Integer opId){
                this.opId=opId;
        }
        public Integer getOpId(){
            return this.opId;
        }


}