package com.ht.vis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.ht.vis.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogOp<M extends BaseLogOp<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setOpName(String opName) {
		set("op_name", opName);
	}
	
	public String getOpName() {
		return getStr("op_name");
	}

	public void setOpChannel(String opChannel) {
		set("op_channel", opChannel);
	}
	
	public String getOpChannel() {
		return getStr("op_channel");
	}

	public void setReqMethod(String reqMethod) {
		set("req_method", reqMethod);
	}
	
	public String getReqMethod() {
		return getStr("req_method");
	}

	public void setReqIp(String reqIp) {
		set("req_ip", reqIp);
	}
	
	public String getReqIp() {
		return getStr("req_ip");
	}

	public void setReqAt(java.util.Date reqAt) {
		set("req_at", reqAt);
	}
	
	public java.util.Date getReqAt() {
		return get("req_at");
	}

	public void setReqParam(String reqParam) {
		set("req_param", reqParam);
	}
	
	public String getReqParam() {
		return getStr("req_param");
	}

	public void setReqRet(String reqRet) {
		set("req_ret", reqRet);
	}
	
	public String getReqRet() {
		return getStr("req_ret");
	}

}