package com.ht.vis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.ht.vis.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleRes<M extends BaseRoleRes<M>> extends CoreModel<M> implements IBean {

	public void setRoleCode(String roleCode) {
		set("roleCode", roleCode);
	}
	
	public String getRoleCode() {
		return getStr("roleCode");
	}

	public void setResCode(String resCode) {
		set("resCode", resCode);
	}
	
	public String getResCode() {
		return getStr("resCode");
	}

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

}