package com.ht.vis.model.base;

import com.ht.vis.core.CoreModel;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCMeetingPic<M extends BaseCMeetingPic<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setMId(Integer mId) {
		set("mId", mId);
	}
	
	public Integer getMId() {
		return getInt("mId");
	}

	public void setPic(String pic) {
		set("pic", pic);
	}
	
	public String getPic() {
		return getStr("pic");
	}

	public void setType(String type) {
		set("type", type);
	}
	
	public String getType() {
		return getStr("type");
	}

}
