package com.ht.vis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.ht.vis.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDd<M extends BaseDd<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}


	public void setVal(String val) {
		set("val", val);
	}
	
	public String getVal() {
		return getStr("val");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setOpId(Integer opId) {
		set("opId", opId);
	}
	
	public Integer getOpId() {
		return getInt("opId");
	}

	public void setDict(String dict) {
		set("dict", dict);
	}
	
	public String getDict() {
		return getStr("dict");
	}

	public void setIdx(Integer idx) {
		set("idx", idx);
	}
	
	public Integer getIdx() {
		return getInt("idx");
	}

	public void setPId(Long pId) {
		set("pId", pId);
	}
	
	public Long getPId() {
		return getLong("pId");
	}

	public void setLAt(java.util.Date lAt) {
		set("lAt", lAt);
	}
	
	public java.util.Date getLAt() {
		return get("lAt");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}
	
	public java.util.Date getDAt() {
		return get("dAt");
	}

}