package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.Consts;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseCDepartmentStaff;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.template.expr.ast.Const;

import java.util.List;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CDepartmentStaff extends BaseCDepartmentStaff<CDepartmentStaff> {
	public static final CDepartmentStaff dao = new CDepartmentStaff().dao();

	public String getDName(){
		List<CDepartment> list=CDepartment.dao.findByPropEQWithDat("code",getDCode());
		if(list.size()>0){
			return list.get(0).getName();
		}else{
			return Consts.NON_SET;
		}
	}
	public String getJName(){
		if(getJobId()!=null){
			Dd dd= CacheKit.get(Consts.CACHE_NAMES.dd.name(),"id_"+getJobId().intValue());
			return dd.getName();
		}else{
			return Consts.NON_SET;
		}
	}

	public String getHeadStr(){
		return "0".equals(getHead())?"是":"否";
	}
}
