package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseCDepartment;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CDepartment extends BaseCDepartment<CDepartment> {
	public static final CDepartment dao = new CDepartment().dao();

}
