package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseCDepartmentStaff;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CDepartmentStaff extends BaseCDepartmentStaff<CDepartmentStaff> {
	public static final CDepartmentStaff dao = new CDepartmentStaff().dao();

}
