package com.ht.vis.model;

import cn.hutool.core.util.StrUtil;
import com.ht.vis.Consts;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseCInfo;
import com.jfinal.plugin.ehcache.CacheKit;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CInfo extends BaseCInfo<CInfo> {
    public static final CInfo dao = new CInfo().dao();

    public String getCTypeStr() {
        if(getCType()!=null){
            Dd dd= CacheKit.get(Consts.CACHE_NAMES.dd.name(),"id_"+getCType().intValue());
            return dd.getName();
        }else{
        return Consts.NON_SET;
        }
    }

}
