package com.ht.vis.model;

import com.ht.vis.model.base.BaseCMeetingPic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CMeetingPic extends BaseCMeetingPic<CMeetingPic> {
	public static final CMeetingPic dao = new CMeetingPic().dao();
}
