package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseCMettingPic;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CMettingPic extends BaseCMettingPic<CMettingPic> {
	public static final CMettingPic dao = new CMettingPic().dao();

}
