package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseCStaff;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class CStaff extends BaseCStaff<CStaff> {
	public static final CStaff dao = new CStaff().dao();

}
