package com.ht.vis.model;


import com.ht.vis.model.base.BaseLogOp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogOp extends BaseLogOp<LogOp> {
	public static final LogOp dao = new LogOp().dao();
}