package com.ht.vis.model;


import com.ht.vis.model.base.BaseRoleSer;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleSer extends BaseRoleSer<RoleSer> {
	public static final RoleSer dao = new RoleSer().dao();

	public List<RoleSer> findByRoleCode(String roleCode){
		return dao.findByPropEQ("roleCode",roleCode);
	}
	public void delByRoleCode(String roleCode){
		List<RoleSer> roleSerList=dao.findByRoleCode(roleCode);
		for (int i = 0; i < roleSerList.size(); i++) {
			RoleSer roleSer=roleSerList.get(i);
			roleSer.delete();
		}
	}
}