package com.ht.vis.model;

import com.jfinal.plugin.ehcache.CacheKit;
import com.ht.vis.Consts;
import com.ht.vis.model.base.BaseRoleRes;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleRes extends BaseRoleRes<RoleRes> {
	public static final RoleRes dao = new RoleRes().dao();

	public List<RoleRes> findByRoleCode(String roleCode){
		return dao.find("select * from s_role_res where roleCode=?",roleCode);
	}
	public void delByRoleCode(String roleCode){
		List<RoleRes> roleResList=findByRoleCode(roleCode);
		for(RoleRes roleRes:roleResList){
			roleRes.delete();
		}
	}
}