package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseSFileStorage;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class SFileStorage extends BaseSFileStorage<SFileStorage> {
	public static final SFileStorage dao = new SFileStorage().dao();

}
