package com.ht.vis.model;

import cn.hutool.core.util.StrUtil;
import com.ht.vis.Consts;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseSpAssessmentCriteria;
import com.jfinal.plugin.ehcache.CacheKit;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class SpAssessmentCriteria extends BaseSpAssessmentCriteria<SpAssessmentCriteria> {
    public static final SpAssessmentCriteria dao = new SpAssessmentCriteria().dao();

    public String getNormStr() {
        Dd dd=CacheKit.get(Consts.CACHE_NAMES.dd.name(),"id_"+getNorm().toString());
        return dd!=null?dd.getName():null;
    }

    public String getTitleStr() {
        Dd dd=CacheKit.get(Consts.CACHE_NAMES.dd.name(),"id_"+getTitle().toString());
        return dd!=null?dd.getName():null;
    }

    public String getStarsStr() {
        if ("1".equals(getStars()))
            return "一级";
        if ("2".equals(getStars()))
            return "二级";
        if ("3".equals(getStars()))
            return "三级";
        return null;
    }

}
