package com.ht.vis.model;

import com.ht.vis.model.base.BaseUserRole;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole().dao();

	public void delByRoleId(int roleId) {
		List<UserRole> userRoles = dao.find("select id from s_user_role where rId=?", roleId);
		for (UserRole ur : userRoles) {
			ur.delete();
		}
	}

	public void delByUserId(int userId) {
		List<UserRole> userRoles = dao.find("select id from s_user_role where uId=?", userId);
		for (UserRole ur : userRoles) {
			ur.delete();
		}
	}
}