package com.ht.vis.model;


import com.ht.vis.model.Role;
import com.ht.vis.model.base.BaseUser;
import java.util.ArrayList;
import java.util.List;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

	public static final User dao = new User().dao();

	public User findByNickname(String nickname){
		String sql="select * from s_user where nickname=?";
		return dao.findFirst(sql,nickname);
	}

	public String getStatusStr(){
		return super.getStatusStr(getStatus());
	}
	//cAt比较的开始时间
	private String beginCAt;
	//cAt比较的结束时间
	private String endCAt;
	public String getBeginCAt(){
		return StrUtil.isNotBlank(this.beginCAt)?DateKit.getDateTimeBegin(this.beginCAt):null;
	}
	public void setBeginCAt(String begin){
		this.beginCAt=begin;
	}

	public String getEndCAt(){
		return StrUtil.isNotBlank(this.endCAt)?DateKit.getDateTimeEnd(this.endCAt):null;
	}
	public void setEndCAt(String end){
		this.endCAt=end;
	}


	public String[] getUserRoleCodes(){
		List<com.ht.vis.model.Role> roles= com.ht.vis.model.Role.dao.findByLoginnameInCache(getLoginname());
		List<String> roleCodes=new ArrayList<>();
		for (com.ht.vis.model.Role role:roles){
			roleCodes.add(role.getCode());
		}
		return roleCodes.toArray(new String[roleCodes.size()]);
	}

	public List<String> getUserRoleNames(){
		List<com.ht.vis.model.Role> roles= com.ht.vis.model.Role.dao.findByLoginnameInCache(getLoginname());
		List<String> roleNames=new ArrayList<>();
		for (Role role:roles){
			roleNames.add(role.getName());
		}
		return roleNames;
	}


}