package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseVChange;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VChange extends BaseVChange<VChange> {
	public static final VChange dao = new VChange().dao();

}
