package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.Consts;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseVChange;
import com.ht.vis.service.user.UserService;
import com.jfinal.aop.Duang;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VChange extends BaseVChange<VChange> {
	public static final VChange dao = new VChange().dao();
	private UserService userService= Duang.duang(UserService.class.getSimpleName(),UserService.class);
	public String getOpName(){
		User user=userService.findByIdInCache(getOpId());
		return user==null? Consts.NON_SET:user.getNickname();
	}
	public String getPriceStr(){

		return getPrice()!=null?Consts.CURRENCY_FORMAT.format(getPrice()):"0.00";
	}
	public String getFeeStr(){

		return getPrice()!=null?Consts.CURRENCY_FORMAT.format(getFee()):"0.00";
	}
}
