package com.ht.vis.model;

import com.ht.vis.Consts;
import com.ht.vis.model.base.BaseVInfo;
import com.jfinal.plugin.ehcache.CacheKit;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VInfo extends BaseVInfo<VInfo> {
    public static final VInfo dao = new VInfo().dao();

    public String getTypeStr() {
        if ("0".equals(getType()))
            return "公交";
        if ("1".equals(getType()))
            return "校车";
        return null;
    }

    public String getLineStr() {
        if(getLine()!=null) {
            Dd dd = CacheKit.get(Consts.CACHE_NAMES.dd.name(), "id_" + getLine().intValue());
            return dd != null ? dd.getName() : Consts.UN_KNOW;
        }else{
            return Consts.UN_KNOW;
        }
    }

    public String getAreaStr() {
        if(getArea()!=null) {
            Dd dd = CacheKit.get(Consts.CACHE_NAMES.dd.name(), "id_" + getArea().intValue());
            return dd != null ? dd.getName() : Consts.UN_KNOW;
        }else{
            return Consts.UN_KNOW;
        }
    }

    public CInfo getCInfo(){
        return CInfo.dao.findByCodeInCache(getCCode());
    }

}
