package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.Consts;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseVInsurance;
import com.ht.vis.service.user.UserService;
import com.jfinal.aop.Duang;
import com.jfinal.template.expr.ast.Const;

import java.text.DecimalFormat;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VInsurance extends BaseVInsurance<VInsurance> {
	public static final VInsurance dao = new VInsurance().dao();
	private UserService userService= Duang.duang(UserService.class.getSimpleName(),UserService.class);
	public String getOpName(){
		User user=userService.findByIdInCache(getOpId());
		return user==null? Consts.NON_SET:user.getNickname();
	}
	public String getPriceStr(){

        return getPrice()!=null?Consts.CURRENCY_FORMAT.format(getPrice()):"0.00";
	}

}
