package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseVInsurance;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VInsurance extends BaseVInsurance<VInsurance> {
	public static final VInsurance dao = new VInsurance().dao();

}
