package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseVLine;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VLine extends BaseVLine<VLine> {
	public static final VLine dao = new VLine().dao();
	public CInfo getCInfo(){
		return CInfo.dao.findByCodeInCache(getCCode());
	}

}
