package com.ht.vis.model;
import cn.hutool.core.util.StrUtil;
import com.ht.vis.kits.DateKit;
import com.ht.vis.model.base.BaseVPic;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class VPic extends BaseVPic<VPic> {
	public static final VPic dao = new VPic().dao();

}
